### ISSUE TITLE
facebook removed as source?

### ISSUE THREAD

**Issue by citcheese** [megadose/holehe#26]
See that FB was removed bit ago. Any way to add it back? Functionality is still there on site

**Comment by megadose** [comment]
To avoid any problems I decided to remove it, first of all I was told that the behavior of facebook is quite random. I did some tests with accounts with 2FA and without 2FA it never alerted the account but some people told me that on random accounts alerted so to avoid that it alerted I preferred to remove it because when a person makes a legal investigation if the target is alerted it can cause a lot of trouble.
